config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'admins/index'
  end

  namespace :users_backoffice do
    get 'users/index'
  end

  #protect links for users
  namespace :users_backoffice do
    get 'welcome/index'
    resources :users, only: [:edit, :update]
    resources :agendas
    get 'schedules/index'
  end
  devise_for :users

  #protect links for admins
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :users
    resources :admins
    resources :courses
    resources :schedules
    resources :students
  end
  devise_for :admins

  get 'inicio', to: 'welcome#index'

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user, inverse_of: :schedules
  belongs_to :course, inverse_of: :schedules
  has_many :class_rooms, inverse_of: :schedule, dependent: :delete_all

  accepts_nested_attributes_for :class_rooms, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  before_action :verify_password, only: [:update]


  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to admins_backoffice_admins_path, notice: 'Administrador(a) foi craido(a) com sucesso!' }
        format.json { render status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to admins_backoffice_admins_path, notice: 'Administrador(a) foi atualizado(a) com sucesso!' }
        format.json { render status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_admins_path, notice: 'Administrador(a) foi deletado(a) com sucesso!' }
      format.json { head :no_content }
    end
  end

  private

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/admins_backoffice/courses_controller.rb
class AdminsBackoffice::CoursesController < AdminsBackofficeController
  before_action :set_course, only: [:edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to admins_backoffice_courses_path, notice: 'Matéria foi criada com sucesso!'}
        format.json { render status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to admins_backoffice_courses_path, notice: 'Matéria foi atualizada com sucesso!' }
        format.json { render status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_courses_path, notice: 'Matéria foi deletada com sucesso!' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:code_c, :description, :ideal_year)
  end
end

app/controllers/admins_backoffice/schedules_controller.rb
class AdminsBackoffice::SchedulesController < AdminsBackofficeController
  before_action :set_schedule, only: [:edit, :update, :destroy]
  before_action :set_user_options, only: [:new, :create, :edit, :update]
  before_action :set_course_options, only: [:new, :create, :edit, :update]
  before_action :set_student_options, only: [:new, :create, :edit, :update]
  before_action :set_notice_update, only: [:update]
  before_action :set_notice_create, only: [:create]
  before_action :verify_time, only: [:create, :update]
  before_action :verify_time_end, only: [:create, :update]
  before_action :verify_day, only: [:create, :update]
  before_action :agenda_validation, only: [:create, :update]
  before_action :time_validation, only: [:create, :update]
  before_action :group_validation, only: [:create]
  before_action :class_schedule, only: [:create]
  before_action :professor_class_time, only: [:create]
  before_action :update_professor_class_time, only: [:update]
  before_action :no_change_time, only: [:update]
  before_action :student_class_conflict_on_update, only: [:update]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  # @block &&
  def create
    @schedule = Schedule.new(schedule_params)
    respond_to do |format|
      if @block && @schedule.save
        student_class_conflict_on_create
        format.html { redirect_to admins_backoffice_schedules_path, notice: @notice }
        format.json { render status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @block && @schedule.update(schedule_params)
        format.html { redirect_to admins_backoffice_schedules_path, notice: @notice }
        format.json { render status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_schedules_path, notice: 'Horário foi deletado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private

  def set_notice_create
    @notice = 'Horário foi criado com sucesso!'
  end

  def set_notice_update
    @notice = 'Horário foi atualizado com sucesso!'
  end

  def set_user_options
    @user_options = User.all.pluck(:description, :id)
  end

  def set_course_options
    @course_options = Course.all.pluck(:description, :code_c)
  end

  def set_student_options
    @student_options = Student.all.pluck(:description, :ar)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def schedule_params
    params.require(:schedule).permit(:user_id, :course_id, :weekday,
                                     :time, :time_end, :group, class_rooms_attributes: [:id, :student_id, :_destroy])
  end

  def verify_time
    case schedule_params[:time]
    when '07:30'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).morning_one
    when '08:20'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).morning_two
    when '09:10'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).morning_three
    when '10:10'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).morning_four
    when '11:00'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).morning_five
    when '13:20'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_one
    when '14:10'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_two
    when '15:00'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_three
    when '16:00'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_four
    when '16:50'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_five
    when '17:40'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_six
    when '18:50'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).evening_one
    when '19:40'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).evening_two
    when '20:30'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).evening_three
    when '21:30'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).evening_four
    when '22:30'
      @aux_time = Agenda.find_by(user_id: schedule_params[:user_id]).evening_five
    end
  end

  def verify_time_end
    case schedule_params[:time_end]
    when '07:30'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).morning_one
    when '08:20'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).morning_two
    when '09:10'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).morning_three
    when '10:10'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).morning_four
    when '11:00'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).morning_five
    when '13:20'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_one
    when '14:10'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_two
    when '15:00'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_three
    when '16:00'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_four
    when '16:50'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_five
    when '17:40'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).afternoon_six
    when '18:50'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).evening_one
    when '19:40'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).evening_two
    when '20:30'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).evening_three
    when '21:30'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).evening_four
    when '22:30'
      @aux_time_end = Agenda.find_by(user_id: schedule_params[:user_id]).evening_five
    end
  end

  def verify_day
    case schedule_params[:weekday]
    when 'Segunda-feira'
      @aux_week = 0
    when 'Terca-feira'
      @aux_week = 1
    when 'Quarta-feira'
      @aux_week = 2
    when 'Quinta-feira'
      @aux_week = 3
    when 'Sexta-feira'
      @aux_week = 4
    when 'Sabado'
      @aux_week = 5
    end
  end

  # @return [FalseClass, TrueClass]
  def agenda_validation
    @block = true
    unless @aux_time.nil?
      @aux_time.each_char do |t|
        if t == @aux_week.to_s
          @block = false
          @notice = "Confira a agenda do Professor #{User.find(schedule_params[:user_id]).description}"
        end
      end
    end
    unless @aux_time_end.nil?
      @aux_time_end.each_char do |te|
        if te == @aux_week.to_s
          @block = false
          @notice = "Confira a agenda do Professor #{User.find(schedule_params[:user_id]).description}"
        end
      end
    end
  end

  def time_validation
    if schedule_params[:time] >= schedule_params[:time_end]
      @block = false
      @notice = 'Hora de início da aula não pode ser depois ou igual do fim da aula.'
    end
  end

  def group_validation
    Schedule.where(course_id: schedule_params[:course_id]).each do |schedule|
      if schedule.group == schedule_params[:group] && schedule.time == schedule_params[:time] && schedule.time_end == schedule_params[:time_end]
        @block = false
        @notice = "A turma #{schedule_params[:group]} já existe neste horário!"
      end
    end
  end

  def class_schedule
    Schedule.where(weekday: schedule_params[:weekday]).each do |schedule|
      if (schedule.group.empty? || schedule_params[:group].empty?) && (Course.find(schedule.course_id).ideal_year == Course.find(schedule_params[:course_id]).ideal_year)
        if schedule.weekday == schedule_params[:weekday]
          unless (schedule_params[:time] < schedule.time && schedule.time > schedule_params[:time_end]) || (schedule_params[:time] < schedule.time_end && schedule.time_end > schedule_params[:time_end])
            unless schedule_params[:time] > schedule.time && schedule.time < schedule_params[:time_end]
              @block = false
              @notice = "Horário ocupado!"
            end
            unless schedule_params[:time] >= schedule.time_end && schedule.time_end < schedule_params[:time_end]
              @block = false
              @notice = "Horário ocupado!"
            end
          end
        end
      end
    end
  end

  def professor_class_time
    schedules = Schedule.where(user_id: schedule_params[:user_id])
    schedules.each do |schedule|
      if schedule.weekday == schedule_params[:weekday]
        unless (schedule_params[:time] < schedule.time && schedule.time > schedule_params[:time_end]) || (schedule_params[:time] < schedule.time_end && schedule.time_end > schedule_params[:time_end])
          unless schedule_params[:time] > schedule.time && schedule.time < schedule_params[:time_end]
            @block = false
            @notice = "Confira os horários de aula do Professor #{User.find(schedule_params[:user_id]).description}"
          end

app/controllers/admins_backoffice/students_controller.rb
class AdminsBackoffice::StudentsController < AdminsBackofficeController
  before_action :set_student, only: [:edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to admins_backoffice_students_path, notice: 'Estudante foi craido(a) com sucesso!' }
        format.json { render status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to admins_backoffice_students_path, notice: 'Estudante foi atualizado(a) com sucesso!' }
        format.json { render status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_students_path, notice: 'Estudante foi deletado(a) com sucesso!' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:ar, :description, :year)
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin_backoffice'
end

app/controllers/users_backoffice/schedules_controller.rb
class UsersBackoffice::SchedulesController < UsersBackofficeController

  def index
    @schedules = Schedule.all
    @check = false
  end
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/agenda_helper.rb
module AdminsBackoffice::AgendaHelper
end

app/helpers/admins_backoffice/users_helper.rb
module AdminsBackoffice::UsersHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_backoffice/schedules_helper.rb
module UsersBackoffice::SchedulesHelper
end

app/views/admins_backoffice/schedules/_class_room_fields.html.erb
<div class="nested-fields">

  <div class="form-group">
    <%= f.label :student_id, class: "control-label col-md-3 col-sm-3 col-xs-12"%>
    <div class="col-md-6 col-sm-6 col-xs-12" >
      <%= f.select :student_id, @student_options, include_blank: true %>   <%= link_to_remove_association('Remover', f) %>
    </div>
  </div>




</div>

app/views/admins_backoffice/schedules/_form.html.erb
<% if schedule.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

    <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admins_backoffice, @schedule], local: true, class: "form-horizontal form-label-left") do |form| %>

  <div class="form-group">
    <%= form.label :user_id, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :user_id, @user_options, include_blank: true, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :course_id, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :course_id, @course_options, include_blank: true, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :weekday, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :weekday, ['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sabado'], include_blank: true, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :group, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :group, ['A', 'B', 'C', 'D'], include_blank: true, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :time, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :time, ['07:30', '08:20', '09:10', '10:10', '11:00', '13:20', '14:10', '15:00', '16:00', '16:50', '17:40', '18:50', '19:40', '20:30', '21:30', '22:30'], include_blank: true, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :time_end, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :time_end, ['07:30', '08:20', '09:10', '10:10', '11:00', '13:20', '14:10', '15:00', '16:00', '16:50', '17:40', '18:50', '19:40', '20:30', '21:30', '22:30'], include_blank: true, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <div id="class_rooms">
      <%= form.fields_for :class_rooms, class: "control-label col-md-3 col-sm-3 col-xs-12" do |class_room| %>
        <%= render partial: "class_room_fields", locals: {f: class_room} %>
      <% end %>

      <%= link_to_add_association form, :class_rooms do %>
        <button class="btn btn-primary">Adicionar aluno em dependência</button>
      <% end %>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 offset-md-3">
      <button type="submit" class="btn btn-success">Submit</button>
    </div>
  </div>
<% end %>

app/views/admins_backoffice/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<div class="col-md-6 col-sm-6 offset-md-3">
  <%= link_to admins_backoffice_schedules_path do %>
    <button class="btn btn-primary">Voltar</button>
  <% end %>
</div>

app/views/admins_backoffice/schedules/index.html.erb
<h1>Horários</h1><br><br>

<%= link_to new_admins_backoffice_schedule_path do %>
  <i class="fa fa-plus"></i> Novo
<% end %>

<div class="x_content">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= @schedules.human_attribute_name(:professor) %></th>
      <th><%= @schedules.human_attribute_name(:course) %></th>
      <th>Estudantes</th>
      <th><%= @schedules.human_attribute_name(:weekday) %></th>
      <th><%= @schedules.human_attribute_name(:group) %></th>
      <th><%= @schedules.human_attribute_name(:time) %></th>
      <th><%= @schedules.human_attribute_name(:time_end) %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= User.find(schedule.user_id).description %></td>
        <td><%= Course.find(schedule.course_id).description %></td>

        <% if !ClassRoom.where(schedule_id: schedule.id).nil? %>
          <td>
            <% ClassRoom.where(schedule_id: schedule.id).each do |classroom| %>
              <% unless classroom.student_id.nil? %>
                <%= Student.find(classroom.student_id).description %>,</br>
              <% end %>
            <% end %>
          </td>
        <% else %>
          <td></td>
        <% end %>

        <td><%= schedule.weekday %></td>
        <td><%= schedule.group %></td>
        <td><%= schedule.time %></td>
        <td><%= schedule.time_end %></td>
        <td>
          <%= link_to edit_admins_backoffice_schedule_path(schedule) do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        </td>
        <td>
          <%= link_to admins_backoffice_schedule_path(schedule), method: :delete, data: {confirm: 'Você tem certeza?'} do %>
            <i class="fa fa-minus"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admins_backoffice/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<div class="col-md-6 col-sm-6 offset-md-3">
  <%= link_to admins_backoffice_schedules_path do %>
    <button class="btn btn-primary">Voltar</button>
  <% end %>
</div>